### ISSUE TITLE
Feature: Add compatibility hook for mysql-server based install on RHEL7

### ISSUE THREAD

**Issue by terackspace** [iuscommunity-pkg/mariadb100u#2]
RHEL7 now ships with MariaDB 5.5, however many users are used to typing "yum install mysql-server". When connecting IUS MariaDB 10 to the system then running the command, errors such as:

```
Error: mariadb100u-config conflicts with 1:mariadb-libs-5.5.44-2.el7.x86_64
Error: Package: 1:mariadb100u-server-10.0.22-1.ius.el7.x86_64
             Requires: libjemalloc.so.1()(64bit)
Error: Package: 1:mariadb100u-10.0.22-1.ius.el7.x86_64
             Requires: libjemalloc.so.1()(64bit)
```

The correct fix is to type "yum install mariadb-server" and it all works as intended, but as a helpful aide to all the people around the world migrating to RHEL7 it would be nice if a compatibility for when "yum install mysql-server" is used it works properly like the base OS. Slowly folks will learn to type a new command (just like how RH says "redirecting to systemctl..." when using "service foo...") but it takes time to learn new habits.

**Comment by carlwgeorge** [comment]
> works properly like the base OS

The thing is, `yum install mysql-server` does **not** work with just the base OS.

```
# yum --disablerepo=ius,epel install mysql-server
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.den.host-engine.com
 * extras: centos.den.host-engine.com
 * updates: centos.den.host-engine.com
No package mysql-server available.
Error: Nothing to do
```

Here are the provides for the stock package.

```
# repoquery --provides mariadb-server
config(mariadb-server) = 1:5.5.44-2.el7.centos
libdaemon_example.so()(64bit)
mariadb-server = 1:5.5.44-2.el7.centos
mariadb-server(x86-64) = 1:5.5.44-2.el7.centos
mysql-compat-server = 1:5.5.44-2.el7.centos
mysql-compat-server(x86-64) = 1:5.5.44-2.el7.centos
```

There is no way for IUS to resolve this, because we can't change the provides of the stock package.  The best course of action is to remove the virtual provides for mysql-server from the IUS mariadb100u package.  This will give stock behavior (nothing) when running `yum install mysql-server`.

**Comment by b-harper** [comment]
I am working on getting updated packages into the testing repositories.

**Comment by b-harper** [comment]
Since 10.0.23-1 release has been in the testing repositories for two weeks and this fix is tiny, we are going to push 10.0.23-2 (which includes this fix) to the stable repositories during tonight automation.

**Comment by carlwgeorge** [comment]
I ran across [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=1282956) which briefly discusses why Red Hat choose not to have `mariadb-server` provide `mysql-server`.  It doesn't change anything for us but it's always nice to add context, even if it's a bit late.

**Comment by carlwgeorge** [comment]
I ran across [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=1282956) which briefly discusses why Red Hat choose not to have `mariadb-server` provide `mysql-server`.  It doesn't change anything for us but it's always nice to add context, even if it's a bit late.
